openapi: 3.0.0
info:
  title: Search API
  version: 1.0.0
servers:
  - url: http://search-api/v1
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
paths:
  /productsWithCategories:
    get:
      parameters:
      - name: description
        in: query
        required: true
        schema:
          type: string
      - name: minPrice
        in: query
        required: true
        schema:
          type: number
      - name: maxPrice
        in: query
        required: true
        schema:
          type: number
      security:
        - basicAuth: []
      summary: Login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: # Request body contents
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    details:
                      type: string
                    category:
                      type: object
                      properties:
                        id: 
                          type: integer
                        name: 
                          type: string
        '403':
          description: Forbidden