openapi: 3.0.0
info:
  title: Users Core Service
  version: 1.0.0
servers:
  - url: http://user-core-service/v1
    description: users core service
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
paths:
  /users:
    post:
      security:
        - basicAuth: []
      summary: Creates a new user
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example: # Sample object
                email: max.mustermann@example.com
                password: 123456
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
    get:
      parameters:
      - name: username
        in: query
        required: true
        schema:
          type: string
      security:
        - basicAuth: []
      summary: Receives information about existing users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: # Request body contents
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    role:
                      type: string                
                  example: # Sample object
                    name: Max Mustermann
                    role: Admin
        '403':
          description: Forbidden
  /users/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
        - basicAuth: []
      summary: Receives information about an existing user
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: # Request body contents
                type: object
                properties:
                  name:
                    type: string
                  role:
                    type: string                
                example: # Sample object
                  name: Max Mustermann
                  role: Admin
        '403':
          description: Forbidden
    put:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
        - BasicAuth: []
      summary: Updates information about an existing user           
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: # Request body contents
                type: object
                properties:
                  name:
                    type: string
                  role:
                    type: string                
                example: # Sample object
                  name: Max Mustermann
                  role: Admin
        '403':
          description: Forbidden
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
        - BasicAuth: []
      summary: Deletes information about an existing user           
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema: # Request body contents
                type: object
                properties:
                  name:
                    type: string
                  role:
                    type: string                
                example: # Sample object
                  name: Max Mustermann
                  role: Admin
        '403':
          description: Forbidden