openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
servers:
  - url: http://users-api/v1
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
paths:
  /users:
    post:
      security:
        - basicAuth: []
      summary: Register
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example: # Sample object
                email: max.mustermann@example.com
                password: 123456
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden