server:
  port: 8004
spring:
  application:
    name: products-core-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"