version: '3'
services:
  eureka-server:
    build: eureka-server/
    ports: 
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
  users-core-service:
    build: users.core.service/
    ports: 
      - 8001:8001
    restart: on-failure
    depends_on:
      - eureka-server
    links:
      - eureka-server
  products-core-service:
    build: products.core.service/
    ports: 
      - 8002:8002 
    depends_on:
      - eureka-server
    links:
      - eureka-server 
  categories-core-service:
    build: categories.core.service/
    ports: 
      - 8003:8003
    depends_on:
      - eureka-server
    links:
      - eureka-server
  products-comp-service:
    build: products.comp.service/
    ports: 
      - 8004:8004
    depends_on:
      - eureka-server
      - categories-core-service
      - products-core-service
    links:
      - eureka-server
  zuul:
    build: zuul-server/
    ports: 
      - 8081:8081
    depends_on:
      - eureka-server
      - products-comp-service
    links:
      - eureka-server
      
  turbine:
    build: turbine/
    ports: 
      - 8082:8082
    depends_on:
      - eureka-server
      - products-comp-service
    links:
      - eureka-server
      
  legacywebshop:
    build:
      context: ../../hska-vis-legacy/
      dockerfile: ../../hska-vis-legacy/docker/Dockerfile
    ports:
      - "8888:8080"
