version: '3'
services:
  users-core-service:
    build: users.core.service/
    ports: 
      - 8001:8001
  products-core-service:
    build: products.core.service/
    ports: 
      - 8002:8002  
  categories-core-service:
    build: categories.core.service/
    ports: 
      - 8003:8003
  products-comp-service:
    build: products.comp.service/
    ports: 
      - 8004:8004
    depends-on:
      - categories-core-service
      - products-core-service
  users-api-service:
    build: users.api.service/
    ports: 
      - 8101:8101
    depends-on:
      - products-comp-service
  products-api-service:
    build: products.api.service/
    ports: 
      - 8102:8102
    depends-on:
      - products-comp-service
  categories-api-service:
    build: categories.api.service/
    ports: 
      - 8103:8103
    depends-on:
      - products-comp-service
  search-api-service:
    build: search.api.service/
    ports: 
      - 8104:8104
    depends-on:
      - products-comp-service
  eureka-server:
    build: eureka-server/
    ports: 
      - 8761:8761
    depends-on:
      - users-api-service
      - categories-api-service
      - products-api-service
      - search-api-service
