server:
  port: 8081
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  ignoredServices: '*'
  routes:
    product-comp-service: /product-comp-service/**
    product-api-service: /product-api-service/**
    user-api-service: /user-api-service/**
    search-api-service: /search-api-service/**
    categories-api-service: /search-api-service/**
