server:
  port: 8081
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  ignoredServices: '*'
  routes:
    products-comp-service:
      path: /products-comp-service/**
      url: http://localhost:8004/products
    products-service:
      path: /products-service/**
      url: http://localhost:8002/products
    users-service:
      path: /users-service/**
      url: http://localhost:8001/users
    categories-service:
      path: /categories-service/**
      url: http://localhost:8003/categories
