server:
  port: 8081
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  ignoredServices: '*'
  routes:
    products-comp-service:
      path: /products-comp-service/**
    products-service:
      path: /products-service/**
    users-service:
      path: /users-service/**
    categories-service:
      path: /categories-service/**
