server:
  port: 8081
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    products-comp-service:
      path: /products-comp-service/**
    products-core-service:
      path: /products-service/**
    users-core-service:
      path: /users-service/**
    categories-core-service:
      path: /categories-service/**
